
spring:
  application:
    name: gateway


eureka:
  instance:
    hostname: localhost

zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    usermanagement:
      path: /users/**
      strip-prefix: false
      serviceId: usermanagement

    userclient:
      path: /userclient/**
      serviceId: userclient
      strip-prefix: false

server:
  port: 8222
