INSERT INTO USER (NAME, USERNAME, PASSWORD) VALUES ('eduardo','emiron', '$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi');
INSERT INTO USER (NAME, USERNAME, PASSWORD) VALUES ('fabiana','fabianadoval', '$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi');
INSERT INTO USER (NAME, USERNAME, PASSWORD) VALUES ('maria clara','mcdoval','$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi');
