server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/emartinsmiron/spring-cloud/config
          username: emartinsmiron
          password: bird89du#
